### ISSUE TITLE
OCPP Error handling

### ISSUE THREAD

**Issue by Nasar165** [Nasar165/ocpp-evse#10]
## Description
add ocpp frame handling and implement error handling 

## Requirements
* add ocpp frames
* add ocpp actions
* add ocpp  function for sending and getting frames.

## Todo
- [x] add ocpp enums for actions and errors 
- [x] add ocpp frames
- [x] add ocpp functions for creating ocpp error frame
- [x] add ocpp functions for fetching ocpp error frames
