### ISSUE TITLE
EVSE

### ISSUE THREAD

**Issue by Nasar165** [Nasar165/ocpp-evse#18]
## Description
add a simple EVSE of the following rating AC 7.7KW simulator. 

## Requirements
* support single connector 
* Status (status notification)
* receive actions from CSMS
* send actions to CSMS
* process OCPP frames into corresponding Call frame

## Todo
- [x] add connector
    - [x] add function to change state 
- [x] add handler to receive messages
- [x] handle inbound message 
     - [x] process ocpp frames request, response and error
         - [x] return error on invalid frame

## Reference
#6  web socket
