### ISSUE TITLE
StopTransaction

### ISSUE THREAD

**Issue by Nasar165** [Nasar165/ocpp-evse#3]
## Description
simulate a stop transaction event

## Requirements
* submit stop transaction request
* user can click to stop transaction

## Todo 
- [x] send transaction inform with transferred amount
- [x] allow user to stop a transaction using the ui
- [x] input transferred value to stop transaction request
- [x] disable button if no stop transaction is on going.
