### ISSUE TITLE
Reconnection strategy

### ISSUE THREAD

**Issue by Nasar165** [Nasar165/ocpp-evse#7]
## Description
A connection might be dropped at anytime during a session and it's critical for us to be able to identify and resume a connection as soon as possible. 

## Requirements
* prevent reconnection spam.
* ability to alter reconnection timeout during runtime.
* identify if a connection is dead or alive.

## Todo
- [x]  Identify dead socket
- [x] set default timeout during boot
- [x] set reconnection timeout
- [ ] use ping - pong strategy to verify connection (Primary)

## Notes
* Ping Pong is no longer necessary see #11 Dead socket

## Relation
#6 WebSocket
