### ISSUE TITLE
RemoteStopTransaction

### ISSUE THREAD

**Issue by Nasar165** [Nasar165/ocpp-evse#9]
## Description
allow a CSMS  to request a remote stop charger event

## Requirements
* start transaction if the state is  not Available or Pending
* Stop transaction if transaction id is available 
* Reject otherwise and do nothing

## Todo
- [x] Reject request if not in Charging state 
- [x] Reject request if transaction id is invalid
- [x] Stop transaction on success
